### PR TITLE
If current directory is complete, be self-contained

### PR DESCRIPTION
**Pull request by gfoury**
When people download or clone this repository from GitHub, they have self-consistent copies of all files. If we already have the files, don't download them a second time. This also avoids unexpected skew against versions of `Tools/` and `Data/`. Then `git pull` (or .zip directory download) becomes the update mechanism.

If we are running inside a complete checkout directory, do all operations inside of it. Experience has shown that users (including this one) are sometimes confused by a separate `~/Library/ssdtPRGen`
directory. This can make remote diagnosis of user error difficult. (Changing branches or restoring `$HOME` from backups seem to be the most frequent causes of error.)

This patch depends on a version of `extractACPITables` that can extract tables into the current directory.

### CODE REVIEW

**Comment by Piker-Alpha** [comment]
Great idea. We should add support for this (target directory feature) but without breaking backward compatibility of the script/tool. Thanks!

Edit: Script and source file updated. Please check if this works for you. We can add the required changes for curl/download checks in a next update (including your makefile).

**Comment by gfoury** [comment]
This looks good to me—I almost used an environment variable instead of pwd too.

I’ll work on the Git voodoo to get this pul request in sync. If you’d like a change faster, lemme know and I’ll just make a fresh branch and do the 3-way merge by hand.

**Comment by Piker-Alpha** [comment]
Thanks. I now also added your Makefile (with a small addition) and the new zipped binary file.

**Comment by gfoury** [comment]
My git-fu is weak. Opening a fresh pull request against head.

**Pull request closed without merging**
